# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        KonomiBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: KonomiBundle:User
                property: user

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: db_provider

            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                success_handler: authentication_handler
            logout:
                path: /logout
                target: /
                success_handler: logout_handler
            remember_me:
                secret:   '%secret%'
                secure:   false # Send cookie via HTTPS
                lifetime: 2592000 # 1 month in seconds
                path:     /
                always_remember_me: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password, roles: ROLE_ADMIN }
        - { path: ^/start, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/calendar, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/statistic, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/edit, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/save, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/new, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/newfix, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
