# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments: ['@service_container', '@security.token_storage', '@security.http_utils', '/']
    logout_handler:
        class: AppBundle\Handler\LogoutHandler
        arguments: ['@service_container', '@security.token_storage', '@security.http_utils', '/']

#    account.security_listener:
#        class: AppBundle\Listener\SecurityListener
#        arguments: ['@service_container']
#        tags:
#            - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthentication }
